library(testthat)
library(tkImgR)


# test_check("tkImgR")
file_path <- system.file("img", "example.png", package = "tkImgR")
tt <- tkImShow(file_path)
Sys.sleep(0.25)
.canvasLeft(tt)
Sys.sleep(0.25)
.canvasControlLeft(tt)
Sys.sleep(0.25)
.canvasRight(tt)
Sys.sleep(0.25)
.zoomUp(tt)
Sys.sleep(0.25)
.zoomUp(tt)
Sys.sleep(0.25)
.canvasControlRight(tt)
Sys.sleep(0.25)
.zoomDown(tt)
Sys.sleep(0.25)
.zoomDown(tt)
Sys.sleep(0.25)
tcltk::tkdestroy(tt)
